---
# Implement your Workload removal tasks here

- name: "Delete keycloak"
  shell: "oc delete keycloak {{app_name}}"

- name: Delete operator.yaml
  command: "oc delete -f https://raw.githubusercontent.com/eformat/keycloak-operator/master/deploy/operator.yaml -n {{ocp_operator_project}}"

- name: Delete rbac.yaml
  command: "oc delete -f https://raw.githubusercontent.com/eformat/keycloak-operator/master/deploy/rbac.yaml -n {{ocp_operator_project}}"

- name: "Delete operator project"
  shell: "oc delete project {{ocp_operator_project}}"

- name: Delete Keycloak_crd
  command: "oc delete crd keycloaks.aerogear.org"

- name: Delete KeycloakRealm_crd
  command: "oc delete crd keycloakrealms.aerogear.org"

# Leave this as the last task in the playbook.
- name: remove_workload tasks complete
  debug:
    msg: "Remove Workload tasks completed successfully."
  when: not silent|bool
